<?php

function geolocation_styles_preprocess_geolocation_views_map(&$variables) {
  // Attaching styles for descriptions on map.
  drupal_add_css(drupal_get_path('module', 'geolocation_styles') . '/css/map_styles.css');
}

/**
 * Implements hook_preprocess_HOOK().
 */
function geolocation_styles_preprocess(&$variables, $hook) {
  if ($hook === 'entity' && isset($variables['events'])) {
    // Get Google API key from site configuration.
    $google_api_key = geolocation_googlemaps_admin_settings()['geolocation_googlemaps_api_key']['#default_value'];
    $google_query = file_get_contents('https://maps.googleapis.com/maps/api/geocode/json?latlng=' . $variables['content']['field_location']['#items'][0]['lat'] . ',' . $variables['content']['field_location']['#items'][0]['lng'] . '&key=' . $google_api_key);
    $encoded = json_decode($google_query);
    if ($encoded->status === 'OK') {
      $event_address = $encoded->results[0]->formatted_address;
    }
    else {
      $event_address = 'Address not recognised';
    }
    // Returns human-readable location string on event page.
    $variables["content"]["field_location"][0]["#markup"] = $event_address;
  }
}